### ISSUE TITLE
Retrieve number of years between 2 PointInTimeInterface

### ISSUE THREAD

**Issue by Orkin** [Innmind/TimeContinuum#1]
Hello @Baptouuuu, I didn't find how to convert a Period in year.

The scope of usage is this one : I would like to retrieve the age (so the number of years between now and a birthdate)

```php
$clock = new Earth();

$clock->now()->elapsedSince($birthday)->milliseconds(); // I retrieve a number in milliseconds
$milliseconds = new Millisecond($milliseconds);

$years = $milliseconds->years(); // retrieve 0
// but $milliseconds->days(); will return something
```

I saw on the code that you didn't convert a number of days to number of years maybe because of leap year. So how can I retrieve the number of years between 2 PointInTime ?

Thanks

**Comment by Baptouuuu** [comment]
Hi Florent,

If you look at the implementation of the period `Millisecond` I use the unit above to compute minutes and so forth. But I stop in `Hour` that computes both the `hours` and `days`, the reason is that the unit above is the month and it's not of a standard length (between `28` and `31`) and the year as well is not _strict_ (`365` or `366`).

That being said in your example `$milliseconds->days()` should return a value higher than `0`. 

So to compute the age you have 2 options:
- the approximative approach: `$milliseconds->days() / 365` (but it will lead to approximative result due to leap years)
- the strict approach: 
```php
$today = $clock->now();
$years = $today->year()->toInt() - $birthday->year()->toInt();
$thisYearBirthday = $birthday->goForward(new Year($years));
if ($thisYearBirthday->aheadOf($today)) {
    $age = --$years;
} else {
    $age = $years;
}
```

Hope it helps :)

**Comment by Orkin** [comment]
Thanks @Baptouuuu, I just updated your exemple to win some lines :

```php
$today = $clock->now();
$age = \abs($today->year()->toInt() - $birthday->year()->toInt());
```
